spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      validation-query: SELECT 1 FROM DUAL
      filters: stat, wall
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root

management:
  server:
    port: 18080
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8081
  error:
    include-stacktrace: always
    include-exception: true
swagger:
  base-package: com.github.taccisum.pigeon.controller
  info:
    title: Pigeon

pigeon:
  version: @project.version@

mybatis-plus:
  mapper-locations: 'classpath:mapper/**.xml'

logging:
  level:
    # 群发消息量过大时会导致出现海量的日志，应默认 info 级别
    pigeon.core.entity.core.message: info
    pigeon.core.entity.core.Message: info
