debug: true
spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/pigeon'
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

pigeon:
  plugins:
    path: /tmp/jars

logging:
  level:
    pigeon.core: debug
    com.github.taccisum.pigeon.controller: debug
#    com.github.taccisum.pigeon.dao.mapper.MessageMapper: debug