name: CD-Run Workflow
on:
  workflow_run:
    workflows: ['CD Workflow']
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Connecting to AliCloud and run latest image.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_PRIVATE_KEY }}
          script: |
            PLUGINS_ROOT=/usr/local/pigeon/plugins
            HOST_LOG_PATH=/var/local/log/${{ github.repository }}
            IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/pigeon
            CONTAINER_NAME=pigeon
            PORT=8082
            mkdir -p $PLUGINS_ROOT
            mkdir -p $HOST_LOG_PATH
            docker pull $IMAGE_TAG
            docker rm -f $CONTAINER_NAME 2&>/dev/null
            docker run \
            -p $PORT:8081 \
            -v $HOST_LOG_PATH:/var/local/log \
            -v $PLUGINS_ROOT:/usrt /local/pigeon/plugins \
            -d \
            --name $CONTAINER_NAME \
            $IMAGE_TAG \
            --spring.profiles.active=prod \
            --spring.datasource.url=jdbc:mysql://${{ secrets.MYSQL_URL }}/pigeon-demo \
            --spring.datasource.username=${{ secrets.MYSQL_USERNAME }} \
            --spring.datasource.password=${{ secrets.MYSQL_PASSWORD }} \
            --pigeon.plugins.path=/usr/local/pigeon/plugins \
            --swagger.enabled=true
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Do nothing beacuse of "CD Workflow" is failure.'
