name: CI Workflow
on:
  push:
    branches:
      - develop
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - run: mvn clean verify -U
